[package]
name = "osom_x64_macros"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
osom_x64_cg = { path = "../osom_x64_cg" }
