[package]
name = "osom_x64_asm"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[dependencies]
paste = { workspace = true }
osom_utils = { path = "../../../libs/osom_utils" }
